Added data_presentation.ipynb with combined plot
ubsuny/CP1-24-HW5 pull request #52
Opened 2024-11-08 05:50 UTC by dhamalakamal

For this assignment all pull requests going  forward should contain the following (please delete the placeholder text and add your own description)

# Title
  - Combined plot of co2 raw data, fft and inverse fft data
   
## Linting
  - Yes, all code follow lint structure.

## Contents
  - Added combined plot for raw data of co2 in timeseries and fft vs inverse fft data
  - new file with `data_presentation.ipynb` is added
  - https://github.com/ubsuny/CP1-24-HW5#task-group-3-data-presentation-max-6-members -> first task

## Labels and Milestones
  - ALL pull requests must have an attached label and Milestone before a reviewer can be assigned.

## Reviewer
  - @laserlab @HeshamElsaman 

Any further questions on formatting pull requests can be asked in the issues tab or on discord. 
This document can be changed at any time.

2024-11-08 13:29 UTC, laserlab commented on data_presentation.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #53.        # Subplot 2: FFT Magnitude vs Frequency
</pre><p>This is not needed, just plot the time docmain</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ubsuny/CP1-24-HW5/pull/52/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2024-11-08 13:30 UTC, laserlab requested changes
- plots have to work
- any data processing needed
- no fft

2024-11-09 03:02 UTC, dhamalakamal commented on data_presentation.ipynb
> +{
No, actually the methods from preparation.py module are not returing data back instead I am getting None value which is why my further code for plotting isn't working. If the method fft_mag returns data correctly, it is expected to work. I can't think of a fix for that unless I understand why it's not returning the fft result back.

2024-11-09 03:06 UTC, dhamalakamal commented on data_presentation.ipynb
> +{
I am getting it like this 
![image](https://github.com/user-attachments/assets/5faf6d3c-4187-4d1c-bbe3-5a480e607b94)

2024-11-18 21:25 UTC, laserlab approved these changes

2024-11-18 21:25 UTC, merged